const ingredients = [
  {
    id: "1",
    key: "whisky",
    name: "Whisky",
    // checked: false,
  },
  {
    id: "2",
    key: "lemon",
    name: "Lemon Juice",
    // checked: false,
  },
  {
    id: "3",
    key: "sugar",
    name: "Sugar",
    // checked: false,
  },
  {
    id: "4",
    key: "angostura",
    name: "Angostura Bitters",
    // checked: false,
  },
  {
    id: "5",
    key: "orangebitters",
    name: "Orange Bitters",
    // checked: false,
  },
  {
    id: "6",
    key: "rum",
    name: "Rum",
    // checked: false,
  },
  {
    id: "7",
    key: "lime",
    name: "Lime Juice",
    // checked: false,
  },
  {
    id: "8",
    key: "greenchartreuse",
    name: "Green Chartreuse",
    // checked: false,
  },
  {
    id: "9",
    key: "maraschino",
    name: "Maraschino Liqueur",
    // checked: false,
  },
  {
    id: "10",
    key: "amaretto",
    name: "Amaretto",
    // checked: false,
  },
  {
    id: "11",
    key: "aperol",
    name: "Aperol",
    // checked: false,
  },
  {
    id: "12",
    key: "applejuice",
    name: "Apple Juice",
    // checked: false,
  },
  {
    id: "13",
    key: "appleliqueur",
    name: "Apple Liqueur",
    // checked: false,
  },
  {
    id: "14",
    key: "apricotbrandy",
    name: "Apricot Brandy",
    // checked: false,
  },
  {
    id: "15",
    key: "bananaliqueur",
    name: "Banana Liqueur",
    // checked: false,
  },
  {
    id: "16",
    key: "beer",
    name: "Beer",
    // checked: false,
  },
  {
    id: "17",
    key: "benedictine",
    name: "Benedictine",
    // checked: false,
  },
  {
    id: "18",
    key: "bourbon",
    name: "Bourbon",
    // checked: false,
  },
  {
    id: "19",
    key: "brandy",
    name: "Brandy",
    // checked: false,
  },
  {
    id: "20",
    key: "cachaca",
    name: "Cachaca",
    // checked: false,
  },
  {
    id: "21",
    key: "calvados",
    name: "Calvados",
    // checked: false,
  },
  {
    id: "22",
    key: "campari",
    name: "Campari",
    // checked: false,
  },
  {
    id: "23",
    key: "cherrybrandy",
    name: "Cherry Brandy",
    // checked: false,
  },
  {
    id: "24",
    key: "chilli",
    name: "Chilli",
    // checked: false,
  },
  {
    id: "25",
    key: "chocolate",
    name: "Chocolate",
    // checked: false,
  },
  {
    id: "26",
    key: "coconutmilk",
    name: "Coconut Milk",
    // checked: false,
  },
  {
    id: "27",
    key: "coconutcream",
    name: "Coconut Cream",
    // checked: false,
  },
  {
    id: "28",
    key: "coffee",
    name: "Coffee",
    // checked: false,
  },
  {
    id: "29",
    key: "coffeeliqueur",
    name: "Coffee Liqueur",
    // checked: false,
  },
  {
    id: "30",
    key: "cognac",
    name: "Cognac",
    // checked: false,
  },
  {
    id: "31",
    key: "cointreau",
    name: "Cointreau",
    // checked: false,
  },
  {
    id: "32",
    key: "cranberryjuice",
    name: "Cranberry Juice",
    // checked: false,
  },
  {
    id: "33",
    key: "cremedecacaod",
    name: "Creme de Cacao Dark",
    // checked: false,
  },
  {
    id: "34",
    key: "cremedecacaow",
    name: "Creme de Cacao White",
    // checked: false,
  },
  {
    id: "35",
    key: "cremedecassis",
    name: "Creme de Cassis",
    // checked: false,
  },
  {
    id: "36",
    key: "cremedementhe",
    name: "Creme de Menthe",
    // checked: false,
  },
  {
    id: "37",
    key: "cremedeviolette",
    name: "Creme de Violette",
    // checked: false,
  },
  {
    id: "38",
    key: "darkrum",
    name: "Dark Rum",
    // checked: false,
  },
  {
    id: "39",
    key: "drambuie",
    name: "Drambuie",
    // checked: false,
  },
  {
    id: "40",
    key: "dryvermouth",
    name: "Dry Vermouth",
    // checked: false,
  },
  {
    id: "41",
    key: "dubonnet",
    name: "Dubonnet",
    // checked: false,
  },
  {
    id: "42",
    key: "eggs",
    name: "Eggs",
    // checked: false,
  },
  {
    id: "43",
    key: "eggwhites",
    name: "Egg Whites",
    // checked: false,
  },
  {
    id: "44",
    key: "frangelico",
    name: "Frangelico",
    // checked: false,
  },
  {
    id: "45",
    key: "galliano",
    name: "Galliano",
    // checked: false,
  },
  {
    id: "46",
    key: "gin",
    name: "Gin",
    // checked: false,
  },
  {
    id: "47",
    key: "gingerbeer",
    name: "Ginger Beer",
    // checked: false,
  },
  {
    id: "48",
    key: "goldschlager",
    name: "Goldschlager",
    // checked: false,
  },
  {
    id: "49",
    key: "grandmarnier",
    name: "Grand Marnier",
    // checked: false,
  },
  {
    id: "50",
    key: "grapefruit",
    name: "Grapefruit",
    // checked: false,
  },
  {
    id: "51",
    key: "grapefruitjuice",
    name: "Grapefruit Juice",
    // checked: false,
  },
  {
    id: "52",
    key: "grenadine",
    name: "Grenadine",
    // checked: false,
  },
  {
    id: "53",
    key: "honey",
    name: "Honey",
    // checked: false,
  },
  {
    id: "54",
    key: "jagermeister",
    name: "Jagermeister",
    // checked: false,
  },
  {
    id: "55",
    key: "maplesyrup",
    name: "Maple Syrup",
    // checked: false,
  },
  {
    id: "56",
    key: "milk",
    name: "Milk",
    // checked: false,
  },
  {
    id: "57",
    key: "mint",
    name: "Mint",
    // checked: false,
  },
  {
    id: "58",
    key: "olives",
    name: "Olives",
    // checked: false,
  },
  {
    id: "59",
    key: "orangeflowerwater",
    name: "Orange Flower Water",
    // checked: false,
  },
  {
    id: "60",
    key: "orangejuice",
    name: "Orange Juice",
    // checked: false,
  },
  {
    id: "61",
    key: "passionfruit",
    name: "Passion Fruit",
    // checked: false,
  },
  {
    id: "62",
    key: "peachliqueur",
    name: "Peach Liqueur",
    // checked: false,
  },
  {
    id: "63",
    key: "peychauds",
    name: "Peychaud's Bitters",
    // checked: false,
  },
  {
    id: "64",
    key: "pimms",
    name: "Pimm's No.1",
    // checked: false,
  },
  {
    id: "65",
    key: "pineapple",
    name: "Pineapple",
    // checked: false,
  },
  {
    id: "66",
    key: "pineapplejuice",
    name: "Pineapple Juice",
    // checked: false,
  },
  {
    id: "67",
    key: "pisco",
    name: "Pisco",
    // checked: false,
  },
  {
    id: "68",
    key: "redwine",
    name: "Red Wine",
    // checked: false,
  },
  {
    id: "69",
    key: "ryewhisky",
    name: "Rye Whiskey",
    // checked: false,
  },
  {
    id: "70",
    key: "sambuca",
    name: "Sambuca",
    // checked: false,
  },
  {
    id: "71",
    key: "scotch",
    name: "Scotch Whisky",
    // checked: false,
  },
  {
    id: "72",
    key: "sodawater",
    name: "Soda Water",
    // checked: false,
  },
  {
    id: "73",
    key: "tabasco",
    name: "Tabasco",
    // checked: false,
  },
  {
    id: "74",
    key: "Tequila",
    name: "Tequila",
    // checked: false,
  },
  {
    id: "75",
    key: "tomatojuice",
    name: "Tomato Juice",
    // checked: false,
  },
  {
    id: "76",
    key: "tonicwater",
    name: "Tonic Water",
    // checked: false,
  },
  {
    id: "77",
    key: "triplesec",
    name: "Triple Sec",
    // checked: false,
  },
  {
    id: "78",
    key: "vanilla",
    name: "Vanilla",
    // checked: false,
  },
  {
    id: "79",
    key: "vodka",
    name: "Vodka",
    // checked: false,
  },
  {
    id: "80",
    key: "whitewine",
    name: "White Wine",
    // checked: false,
  },
  {
    id: "81",
    key: "worcestershire",
    name: "Worcestershire Sauce",
    // checked: false,
  },
  {
    id: "82",
    key: "sweetvermouth",
    name: "Sweet Vermouth",
    // checked: false,
  },
];

export default ingredients;
